#include "stdafx.h"

#include "RengaEntityUIData.h"
#include "GuidMap.h"

#include <Renga/EntityTypes.h>

#include <map>


const RengaEntityUIData getRengaEntityUIData(GUID entityType)
{
  static GuidMap<RengaEntityUIData> dict{
      {Renga::EntityTypes::Wall, {QApplication::translate("me_modelObjects", "Walls"), ":/icons/Wall"}},
      {Renga::EntityTypes::Column, {QApplication::translate("me_modelObjects", "Columns"), ":/icons/Column"}},
      {Renga::EntityTypes::Floor, {QApplication::translate("me_modelObjects", "Floors"), ":/icons/Floor"}},
      {Renga::EntityTypes::Opening, {QApplication::translate("me_modelObjects", "Openings"), ":/icons/Opening"}},
      {Renga::EntityTypes::Roof, {QApplication::translate("me_modelObjects", "Roofs"), ":/icons/Roof"}},
      {Renga::EntityTypes::Beam, {QApplication::translate("me_modelObjects", "Beams"), ":/icons/Beam"}},
      {Renga::EntityTypes::Stair, {QApplication::translate("me_modelObjects", "Stairs"), ":/icons/Stair"}},
      {Renga::EntityTypes::Ramp, {QApplication::translate("me_modelObjects", "Ramps"), ":/icons/Ramp"}},
      {Renga::EntityTypes::Window, {QApplication::translate("me_modelObjects", "Windows"), ":/icons/Window"}},
      {Renga::EntityTypes::Door, {QApplication::translate("me_modelObjects", "Doors"), ":/icons/Door"}},
      {Renga::EntityTypes::Railing, {QApplication::translate("me_modelObjects", "Railings"), ":/icons/Railing"}},
      {Renga::EntityTypes::Room, {QApplication::translate("me_modelObjects", "Rooms"), ":/icons/Room"}},
      {Renga::EntityTypes::IsolatedFoundation,
       {QApplication::translate("me_modelObjects", "Isolated foundations"), ":/icons/Isolated_foundation"}},
      {Renga::EntityTypes::WallFoundation,
       {QApplication::translate("me_modelObjects", "Wall foundations"), ":/icons/Wall_foundation"}},
      {Renga::EntityTypes::AssemblyInstance,
       {QApplication::translate("me_modelObjects", "Assembly instances"), ":/icons/Assembly"}},
      {Renga::EntityTypes::Element, {QApplication::translate("me_modelObjects", "Elements"), ":/icons/Element"}},
      {Renga::EntityTypes::Plate, {QApplication::translate("me_modelObjects", "Plates"), ":/icons/Plate"}},
      {Renga::EntityTypes::RoutePoint,
       {QApplication::translate("me_modelObjects", "RoutePoints"), ":/icons/RoutePoint"}},
      {Renga::EntityTypes::Equipment, {QApplication::translate("me_modelObjects", "Equipment"), ":/icons/Equipment"}},
      {Renga::EntityTypes::PlumbingFixture,
       {QApplication::translate("me_modelObjects", "PlumbingFixtures"), ":/icons/PlumbingFixture"}},
      {Renga::EntityTypes::MechanicalEquipment,
       {QApplication::translate("me_modelObjects", "AirEquipment"), ":/icons/AirEquipment"}},
      {Renga::EntityTypes::Line3D, {QApplication::translate("me_modelObjects", "Lines3D"), ":/icons/Line"}},
      {Renga::EntityTypes::Hatch, {QApplication::translate("me_modelObjects", "Hatches"), ":/icons/Hatch"}},
      {Renga::EntityTypes::ModelText, {QApplication::translate("me_modelObjects", "TextShapes"), ":/icons/Text"}},
      {Renga::EntityTypes::Rebar, {QApplication::translate("me_modelObjects", "Rebars"), ":/icons/Plate"}},
      {Renga::EntityTypes::PipeAccessory,
       {QApplication::translate("me_modelObjects", "PipeAccessories"), ":/icons/PipeAccessory"}},
      {Renga::EntityTypes::PipeFitting,
       {QApplication::translate("me_modelObjects", "PipeFittings"), ":/icons/PipeFitting"}},
      {Renga::EntityTypes::Pipe, {QApplication::translate("me_modelObjects", "Pipes"), ":/icons/Pipe"}},
      {Renga::EntityTypes::Duct, {QApplication::translate("me_modelObjects", "AirDucts"), ":/icons/AirDuct"}},
      {Renga::EntityTypes::DuctAccessory,
       {QApplication::translate("me_modelObjects", "AirAccessories"), ":/icons/AirAccessory"}},
      {Renga::EntityTypes::DuctFitting,
       {QApplication::translate("me_modelObjects", "AirFittings"), ":/icons/AirComponent"}},
      {Renga::EntityTypes::ElectricalCircuitLine,
       {QApplication::translate("me_modelObjects", "LineElectricalCircuits"), ":/icons/LineElectricalCircuit"}},
      {Renga::EntityTypes::LightingFixture,
       {QApplication::translate("me_modelObjects", "LightFixtures"), ":/icons/LightFixture"}},
      {Renga::EntityTypes::ElectricDistributionBoard,
       {QApplication::translate("me_modelObjects", "DistributionBoards"), ":/icons/DistributionBoard"}},
      {Renga::EntityTypes::WiringAccessory,
       {QApplication::translate("me_modelObjects", "WiringAccessories"), ":/icons/WiringAccessory"}},
      {Renga::EntityTypes::Route, {QApplication::translate("me_modelObjects", "Routes"), ":/icons/Route"}},
      {Renga::EntityTypes::Axis, {QApplication::translate("me_modelObjects", "Axes"), ":/icons/Axis"}},
      {Renga::EntityTypes::Elevation, {QApplication::translate("me_modelObjects", "Elevations"), ":/icons/Elevation"}},
      {Renga::EntityTypes::Section, {QApplication::translate("me_modelObjects", "Sections"), ":/icons/Section"}},
      {Renga::EntityTypes::LinearDimension,
       {QApplication::translate("me_modelObjects", "Dimensions"), ":/icons/Dimension"}},
      {Renga::EntityTypes::RadialDimension,
       {QApplication::translate("me_modelObjects", "Dimensions"), ":/icons/Dimension"}},
      {Renga::EntityTypes::DiametralDimension,
       {QApplication::translate("me_modelObjects", "Dimensions"), ":/icons/Dimension"}},
      {Renga::EntityTypes::AngularDimension,
       {QApplication::translate("me_modelObjects", "Dimensions"), ":/icons/Dimension"}},
      {Renga::EntityTypes::Material, {"", ":/icons/Material"}},
      {Renga::EntityTypes::LayeredMaterial, {"", ":/icons/Material"}},
      {Renga::EntityTypes::PlumbingFixtureStyle, {"", ":/icons/i16_plumbing_fixture_style"}},
      {Renga::EntityTypes::EquipmentStyle, {"", ":/icons/i16_mep_equipment_style_editor"}},
      {Renga::EntityTypes::PipeStyle, {"", ":/icons/i16_mep_pipe_style_editor"}},
      {Renga::EntityTypes::PipeFittingStyle, {"", ":/icons/i16_pipe_component_style_editor"}},
      {Renga::EntityTypes::PipeAccessoryStyle, {"", ":/icons/i16_mep_pipe_accessory_style_editor"}},
      {Renga::EntityTypes::MechanicalEquipmentStyle, {"", ":/icons/i16_air_equipment_style_editor"}},
      {Renga::EntityTypes::DuctStyle, {"", ":/icons/i16_airduct_style_editor"}},
      {Renga::EntityTypes::DuctFittingStyle, {"", ":/icons/i16_air_component_style_editor"}},
      {Renga::EntityTypes::DuctAccessoryStyle, {"", ":/icons/i16_mep_air_accessory_style_editor"}},
      {Renga::EntityTypes::WiringAccessoryStyle, {"", ":/icons/i16_wiring_accessory_style_editor"}},
      {Renga::EntityTypes::LightingFixtureStyle, {"", ":/icons/i16_light_fixture_style_editor"}},
      {Renga::EntityTypes::ElectricDistributionBoardStyle,
       {"", ":/icons/i16_electrical_distribution_board_style_editor"}},
      {Renga::EntityTypes::ElectricalConductorStyle, {"", ":/icons/i16_conductors_style_editor"}},
      {Renga::EntityTypes::ElectricCircuitLineStyle, {"", ":/icons/i16_line_electrical_circuit_style_editor"}},
      {Renga::EntityTypes::SystemStyle, {"", ":/icons/i16_mep_system_style_editor"}},
      {Renga::EntityTypes::Assembly, {"", ":/icons/Assembly"}},
  };
  auto dataIt = dict.find(entityType);
  return (dataIt != dict.end()) ? dataIt->second : RengaEntityUIData();
}
